# Generated by Django 5.1.5 on 2025-04-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='images')),
                ('li1', models.CharField(max_length=30)),
                ('li2', models.CharField(max_length=30)),
                ('li3', models.CharField(max_length=30)),
                ('li4', models.CharField(max_length=30)),
                ('li5', models.CharField(max_length=30)),
                ('li6', models.CharField(max_length=30)),
                ('li7', models.CharField(max_length=30)),
                ('li8', models.CharField(max_length=30)),
            ],
        ),
    ]
