# Generated by Django 5.1.5 on 2025-04-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li9', models.CharField(max_length=30)),
                ('li10', models.CharField(max_length=30)),
                ('li11', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=30)),
                ('li12', models.CharField(max_length=30)),
                ('li13', models.CharField(max_length=30)),
                ('li14', models.CharField(max_length=30)),
            ],
        ),
    ]
