# Generated by Django 5.1.5 on 2025-04-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0002_section1'),
    ]

    operations = [
        migrations.CreateModel(
            name='section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_H1', models.CharField(max_length=30)),
                ('box1_img', models.ImageField(upload_to='images')),
                ('box2_h1', models.CharField(max_length=30)),
                ('box2_img', models.ImageField(upload_to='images')),
                ('box3_h1', models.CharField(max_length=30)),
                ('box3_img', models.ImageField(upload_to='images')),
                ('box4_h1', models.CharField(max_length=30)),
                ('box4_img', models.ImageField(upload_to='images')),
                ('box5_h1', models.CharField(max_length=30)),
                ('box5_img', models.ImageField(upload_to='images')),
                ('box6_h1', models.CharField(max_length=30)),
                ('box6_img', models.ImageField(upload_to='images')),
                ('box7_h1', models.CharField(max_length=30)),
                ('box7_img', models.ImageField(upload_to='images')),
                ('box8_h1', models.CharField(max_length=30)),
                ('box8_img', models.ImageField(upload_to='images')),
                ('box9_h1', models.CharField(max_length=30)),
                ('box9_img', models.ImageField(upload_to='images')),
                ('box10_h1', models.CharField(max_length=30)),
                ('box10_img', models.ImageField(upload_to='images')),
                ('box11_h1', models.CharField(max_length=30)),
                ('box11_img', models.ImageField(upload_to='images')),
                ('box12_h1', models.CharField(max_length=30)),
                ('box12_img', models.ImageField(upload_to='images')),
                ('box13_h1', models.CharField(max_length=30)),
                ('box13_img', models.ImageField(upload_to='images')),
                ('box14_h1', models.CharField(max_length=30)),
                ('box14_img', models.ImageField(upload_to='images')),
                ('box15_h1', models.CharField(max_length=30)),
                ('box15_img', models.ImageField(upload_to='images')),
                ('box16_h1', models.CharField(max_length=30)),
                ('box16_img', models.ImageField(upload_to='images')),
                ('box17_h1', models.CharField(max_length=30)),
                ('box17_img', models.ImageField(upload_to='images')),
                ('box18_h1', models.CharField(max_length=30)),
                ('box18_img', models.ImageField(upload_to='images')),
                ('box19_h1', models.CharField(max_length=30)),
                ('box19_img', models.ImageField(upload_to='images')),
                ('box20_h1', models.CharField(max_length=30)),
                ('box20_img', models.ImageField(upload_to='images')),
                ('box21_h1', models.CharField(max_length=30)),
                ('box21_img', models.ImageField(upload_to='images')),
                ('box22_h1', models.CharField(max_length=30)),
                ('box22_img', models.ImageField(upload_to='images')),
                ('box23_h1', models.CharField(max_length=30)),
                ('box23_img', models.ImageField(upload_to='images')),
                ('box24_h1', models.CharField(max_length=30)),
                ('box24_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
