# Generated by Django 5.1.5 on 2025-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0003_section2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_1', models.ImageField(upload_to='images')),
                ('mob_2', models.ImageField(upload_to='images')),
                ('mob_3', models.ImageField(upload_to='images')),
                ('mob_4', models.ImageField(upload_to='images')),
                ('mob_5', models.ImageField(upload_to='images')),
            ],
        ),
    ]
