# Generated by Django 5.1.5 on 2025-04-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0004_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedmiSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_1', models.ImageField(upload_to='images')),
                ('red_2', models.ImageField(upload_to='images')),
                ('red_3', models.ImageField(upload_to='images')),
                ('red_4', models.ImageField(upload_to='images')),
                ('red_5', models.ImageField(upload_to='images')),
            ],
        ),
    ]
