# Generated by Django 5.1.5 on 2025-04-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0005_redmiseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='poco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poco_1', models.ImageField(upload_to='images')),
                ('poco_2', models.ImageField(upload_to='images')),
                ('poco_3', models.ImageField(upload_to='images')),
                ('poco_4', models.ImageField(upload_to='images')),
                ('poco_5', models.ImageField(upload_to='images')),
            ],
        ),
    ]
