# Generated by Django 5.1.5 on 2025-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0006_poco'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_1', models.ImageField(upload_to='images')),
                ('tablet_2', models.ImageField(upload_to='images')),
                ('tablet_3', models.ImageField(upload_to='images')),
                ('tablet_4', models.ImageField(upload_to='images')),
                ('tablet_5', models.ImageField(upload_to='images')),
            ],
        ),
    ]
