# Generated by Django 5.1.5 on 2025-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0007_tablets'),
    ]

    operations = [
        migrations.CreateModel(
            name='lapSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapSeries1', models.ImageField(upload_to='images')),
                ('lapSeries2', models.ImageField(upload_to='images')),
                ('lapSeries3', models.ImageField(upload_to='images')),
                ('lapSeries4', models.ImageField(upload_to='images')),
                ('lapSeries5', models.ImageField(upload_to='images')),
            ],
        ),
    ]
