# Generated by Django 5.1.5 on 2025-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0008_lapseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watches1', models.ImageField(upload_to='images')),
                ('watches_h1', models.CharField(max_length=30)),
                ('watches2', models.ImageField(upload_to='images')),
                ('watches_h2', models.CharField(max_length=30)),
                ('watches3', models.ImageField(upload_to='images')),
                ('watches_h3', models.CharField(max_length=30)),
                ('watches4', models.ImageField(upload_to='images')),
                ('watches_h4', models.CharField(max_length=30)),
                ('watches5', models.ImageField(upload_to='images')),
                ('watches_h5', models.CharField(max_length=30)),
            ],
        ),
    ]
