# Generated by Django 5.1.5 on 2025-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0009_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='bands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bands1', models.ImageField(upload_to='images')),
                ('bands_h1', models.CharField(max_length=30)),
                ('bands2', models.ImageField(upload_to='images')),
                ('bands_h2', models.CharField(max_length=30)),
                ('bands3', models.ImageField(upload_to='images')),
                ('bands_h3', models.CharField(max_length=30)),
                ('bands4', models.ImageField(upload_to='images')),
                ('bands_h4', models.CharField(max_length=30)),
                ('bands5', models.ImageField(upload_to='images')),
                ('bands_h15', models.CharField(max_length=30)),
            ],
        ),
    ]
