# Generated by Django 5.1.5 on 2025-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0010_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Earphn1', models.ImageField(upload_to='images')),
                ('Earphn_h1', models.CharField(max_length=30)),
                ('Earphn2', models.ImageField(upload_to='images')),
                ('Earphn_h2', models.CharField(max_length=30)),
                ('Earphn3', models.ImageField(upload_to='images')),
                ('Earphn_h3', models.CharField(max_length=30)),
                ('Earphn4', models.ImageField(upload_to='images')),
                ('Earphn_h4', models.CharField(max_length=30)),
                ('Earphn5', models.ImageField(upload_to='images')),
                ('Earphn_h5', models.CharField(max_length=30)),
            ],
        ),
    ]
