# Generated by Django 5.1.5 on 2025-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0011_earphones'),
    ]

    operations = [
        migrations.CreateModel(
            name='pocoF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocoF1', models.ImageField(upload_to='images')),
                ('pocoF1_h1', models.CharField(max_length=30)),
                ('pocoF2', models.ImageField(upload_to='images')),
                ('pocoF1_h2', models.CharField(max_length=30)),
                ('pocoF3', models.ImageField(upload_to='images')),
                ('pocoF1_h3', models.CharField(max_length=30)),
                ('pocoF4', models.ImageField(upload_to='images')),
                ('pocoF1_h4', models.CharField(max_length=30)),
                ('pocoF5', models.ImageField(upload_to='images')),
                ('pocoF1_h5', models.CharField(max_length=30)),
            ],
        ),
    ]
