# Generated by Django 5.1.5 on 2025-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0012_pocof'),
    ]

    operations = [
        migrations.CreateModel(
            name='pocox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocox1', models.ImageField(upload_to='images')),
                ('pocox1_h1', models.CharField(max_length=30)),
                ('pocox2', models.ImageField(upload_to='images')),
                ('pocox1_h2', models.CharField(max_length=30)),
                ('pocox3', models.ImageField(upload_to='images')),
                ('pocox1_h3', models.CharField(max_length=30)),
                ('pocox4', models.ImageField(upload_to='images')),
                ('pocox1_h4', models.CharField(max_length=30)),
                ('pocox5', models.ImageField(upload_to='images')),
                ('pocox1_h5', models.CharField(max_length=30)),
            ],
        ),
    ]
