# Generated by Django 5.1.5 on 2025-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0013_pocox'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New1', models.ImageField(upload_to='images')),
                ('New1_h1', models.CharField(max_length=30)),
            ],
        ),
    ]
