# Generated by Django 5.1.5 on 2025-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0014_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='picX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POCOX1', models.ImageField(upload_to='images')),
                ('POCOX1_h1', models.ImageField(upload_to='images')),
                ('POCOX2', models.ImageField(upload_to='images')),
                ('POCOX1_h2', models.ImageField(upload_to='images')),
                ('POCOX3', models.ImageField(upload_to='images')),
                ('POCOX1_h3', models.ImageField(upload_to='images')),
                ('POCOX4', models.ImageField(upload_to='images')),
                ('POCOX1_h4', models.ImageField(upload_to='images')),
                ('POCOX5', models.ImageField(upload_to='images')),
                ('POCOX1_h5', models.ImageField(upload_to='images')),
            ],
        ),
    ]
