# Generated by Django 5.1.5 on 2025-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0015_picx'),
    ]

    operations = [
        migrations.CreateModel(
            name='picM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POCOM1', models.ImageField(upload_to='images')),
                ('POCOM1_h1', models.CharField(max_length=30)),
                ('POCOM2', models.ImageField(upload_to='images')),
                ('POCOM1_h2', models.CharField(max_length=30)),
                ('POCOM3', models.ImageField(upload_to='images')),
                ('POCOM1_h3', models.CharField(max_length=30)),
                ('POCOM4', models.ImageField(upload_to='images')),
                ('POCOM1_h4', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='picx',
            name='POCOX1_h1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='picx',
            name='POCOX1_h2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='picx',
            name='POCOX1_h3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='picx',
            name='POCOX1_h4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='picx',
            name='POCOX1_h5',
            field=models.CharField(max_length=30),
        ),
    ]
