# Generated by Django 5.1.5 on 2025-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0016_picm_alter_picx_pocox1_h1_alter_picx_pocox1_h2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='picS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picS1', models.ImageField(upload_to='images')),
                ('picS1_h1', models.ImageField(upload_to='images')),
                ('picS2', models.ImageField(upload_to='images')),
                ('picS1_h2', models.ImageField(upload_to='images')),
                ('picS3', models.ImageField(upload_to='images')),
                ('picS1_h3', models.ImageField(upload_to='images')),
            ],
        ),
    ]
