# Generated by Django 5.1.5 on 2025-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0017_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignBackGroundImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SignBackGroundImg1', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='pics',
            name='picS1_h1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pics',
            name='picS1_h2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pics',
            name='picS1_h3',
            field=models.CharField(max_length=30),
        ),
    ]
