# Generated by Django 5.1.5 on 2025-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0018_signbackgroundimg_alter_pics_pics1_h1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_inlogoImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_inlogoImg1', models.ImageField(upload_to='images')),
            ],
        ),
    ]
