# Generated by Django 5.1.5 on 2025-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiomi1', '0019_sign_inlogoimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_upImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_upBackground_Img', models.ImageField(upload_to='images')),
                ('sign_up_LogoImg', models.ImageField(upload_to='images')),
            ],
        ),
    ]
